//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TocTocToc.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TocTocToc.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bla.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TocTocToc application bla bla bla .....
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to বাংলা.
        /// </summary>
        internal static string Bengali {
            get {
                return ResourceManager.GetString("Bengali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中国人.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हिन्दी.
        /// </summary>
        internal static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        internal static string HttpError500 {
            get {
                return ResourceManager.GetString("HttpError500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable..
        /// </summary>
        internal static string HttpError503 {
            get {
                return ResourceManager.GetString("HttpError503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a valid character.
        /// </summary>
        internal static string IncorrectChar {
            get {
                return ResourceManager.GetString("IncorrectChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the words separated by &apos;,&apos; or &apos;;&apos;.
        /// </summary>
        internal static string IncorrectSeparatorCharacter {
            get {
                return ResourceManager.GetString("IncorrectSeparatorCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a valid word.
        /// </summary>
        internal static string IncorrectValidWord {
            get {
                return ResourceManager.GetString("IncorrectValidWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition of the word is incorrect. Please write a correct word.
        /// </summary>
        internal static string IncorrectWordDefinition {
            get {
                return ResourceManager.GetString("IncorrectWordDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Word Spelling.
        /// </summary>
        internal static string IncorrectWordSpelling {
            get {
                return ResourceManager.GetString("IncorrectWordSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahasa Indonesia.
        /// </summary>
        internal static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address has been activated.
        /// </summary>
        internal static string IsActiveAddress {
            get {
                return ResourceManager.GetString("IsActiveAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of the place are incomplete.
        /// </summary>
        internal static string IsAreaSelectedIncomplete {
            get {
                return ResourceManager.GetString("IsAreaSelectedIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete an activated address.
        /// </summary>
        internal static string IsDeleteActiveAddressInvalid {
            get {
                return ResourceManager.GetString("IsDeleteActiveAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete an empty address list.
        /// </summary>
        internal static string IsEmptyAddressInvalid {
            get {
                return ResourceManager.GetString("IsEmptyAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to delete, You need at list one address.
        /// </summary>
        internal static string IsOneAddressNeeded {
            get {
                return ResourceManager.GetString("IsOneAddressNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is need it.
        /// </summary>
        internal static string IsPayedNeed {
            get {
                return ResourceManager.GetString("IsPayedNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to update the media.
        /// </summary>
        internal static string IsUpdatedMediaFalse {
            get {
                return ResourceManager.GetString("IsUpdatedMediaFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiana.
        /// </summary>
        internal static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an address.
        /// </summary>
        internal static string LabelAddAddress {
            get {
                return ResourceManager.GetString("LabelAddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Modify an address.
        /// </summary>
        internal static string LabelAddModifyAddress {
            get {
                return ResourceManager.GetString("LabelAddModifyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        internal static string LabelAddPhoto {
            get {
                return ResourceManager.GetString("LabelAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string LabelAddress1 {
            get {
                return ResourceManager.GetString("LabelAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string LabelAddress2 {
            get {
                return ResourceManager.GetString("LabelAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        internal static string LabelAddress3 {
            get {
                return ResourceManager.GetString("LabelAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name your address.
        /// </summary>
        internal static string LabelAddressNamed {
            get {
                return ResourceManager.GetString("LabelAddressNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a media.
        /// </summary>
        internal static string LabelAdvertisingAddMedia {
            get {
                return ResourceManager.GetString("LabelAdvertisingAddMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LabelAdvertisingName {
            get {
                return ResourceManager.GetString("LabelAdvertisingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update media.
        /// </summary>
        internal static string LabelAdvertisingUpdateMedia {
            get {
                return ResourceManager.GetString("LabelAdvertisingUpdateMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string LabelAge {
            get {
                return ResourceManager.GetString("LabelAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target locations.
        /// </summary>
        internal static string LabelArea {
            get {
                return ResourceManager.GetString("LabelArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string LabelBirthdate {
            get {
                return ResourceManager.GetString("LabelBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget / Duration.
        /// </summary>
        internal static string LabelBudget {
            get {
                return ResourceManager.GetString("LabelBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        internal static string LabelBuildingEntrance {
            get {
                return ResourceManager.GetString("LabelBuildingEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Name.
        /// </summary>
        internal static string LabelBuildingName {
            get {
                return ResourceManager.GetString("LabelBuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number.
        /// </summary>
        internal static string LabelBuildingNumber {
            get {
                return ResourceManager.GetString("LabelBuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        internal static string LabelDeleteAccount {
            get {
                return ResourceManager.GetString("LabelDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisrt name.
        /// </summary>
        internal static string LabelFirstname {
            get {
                return ResourceManager.GetString("LabelFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string LabelFloor {
            get {
                return ResourceManager.GetString("LabelFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string LabelGender {
            get {
                return ResourceManager.GetString("LabelGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My position.
        /// </summary>
        internal static string LabelGeolocPosition {
            get {
                return ResourceManager.GetString("LabelGeolocPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string LabelHistory {
            get {
                return ResourceManager.GetString("LabelHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the address type.
        /// </summary>
        internal static string LabelHousingType {
            get {
                return ResourceManager.GetString("LabelHousingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest.
        /// </summary>
        internal static string LabelInterest {
            get {
                return ResourceManager.GetString("LabelInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests.
        /// </summary>
        internal static string LabelInterests {
            get {
                return ResourceManager.GetString("LabelInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LabelLanguages {
            get {
                return ResourceManager.GetString("LabelLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LabelLastname {
            get {
                return ResourceManager.GetString("LabelLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LabelLogout {
            get {
                return ResourceManager.GetString("LabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status.
        /// </summary>
        internal static string LabelMaritalStatus {
            get {
                return ResourceManager.GetString("LabelMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string LabelNotification {
            get {
                return ResourceManager.GetString("LabelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string LabelPayment {
            get {
                return ResourceManager.GetString("LabelPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string LabelPreview {
            get {
                return ResourceManager.GetString("LabelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string LabelPrivacy {
            get {
                return ResourceManager.GetString("LabelPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string LabelProfession {
            get {
                return ResourceManager.GetString("LabelProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the application.
        /// </summary>
        internal static string LabelRateApp {
            get {
                return ResourceManager.GetString("LabelRateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend.
        /// </summary>
        internal static string LabelRecommend {
            get {
                return ResourceManager.GetString("LabelRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        internal static string LabelReport {
            get {
                return ResourceManager.GetString("LabelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence Name.
        /// </summary>
        internal static string LabelResidenceName {
            get {
                return ResourceManager.GetString("LabelResidenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string LabelSecurity {
            get {
                return ResourceManager.GetString("LabelSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show age.
        /// </summary>
        internal static string LabelShowAge {
            get {
                return ResourceManager.GetString("LabelShowAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show floor.
        /// </summary>
        internal static string LabelShowFloor {
            get {
                return ResourceManager.GetString("LabelShowFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show marital status.
        /// </summary>
        internal static string LabelShowMaritalStatus {
            get {
                return ResourceManager.GetString("LabelShowMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show profession.
        /// </summary>
        internal static string LabelShowProfession {
            get {
                return ResourceManager.GetString("LabelShowProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string LabelState {
            get {
                return ResourceManager.GetString("LabelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Number.
        /// </summary>
        internal static string LabelStreetNumber {
            get {
                return ResourceManager.GetString("LabelStreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string LabelTermConditions {
            get {
                return ResourceManager.GetString("LabelTermConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an address.
        /// </summary>
        internal static string LabelTitleAddAddress {
            get {
                return ResourceManager.GetString("LabelTitleAddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a sign.
        /// </summary>
        internal static string LabelTitleAddDirectory {
            get {
                return ResourceManager.GetString("LabelTitleAddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an event.
        /// </summary>
        internal static string LabelTitleAddEvent {
            get {
                return ResourceManager.GetString("LabelTitleAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a post.
        /// </summary>
        internal static string LabelTitleAddPost {
            get {
                return ResourceManager.GetString("LabelTitleAddPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a rental.
        /// </summary>
        internal static string LabelTitleAddRental {
            get {
                return ResourceManager.GetString("LabelTitleAddRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Addresses.
        /// </summary>
        internal static string LabelTitleAddress {
            get {
                return ResourceManager.GetString("LabelTitleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a call for solidarity.
        /// </summary>
        internal static string LabelTitleAddSolidarityCall {
            get {
                return ResourceManager.GetString("LabelTitleAddSolidarityCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an offer to solidarity.
        /// </summary>
        internal static string LabelTitleAddSolidarityOffer {
            get {
                return ResourceManager.GetString("LabelTitleAddSolidarityOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        internal static string LabelTitleAdvertisement {
            get {
                return ResourceManager.GetString("LabelTitleAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string LabelTitleBlog {
            get {
                return ResourceManager.GetString("LabelTitleBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My communities.
        /// </summary>
        internal static string LabelTitleCommunity {
            get {
                return ResourceManager.GetString("LabelTitleCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LabelTitleConnection {
            get {
                return ResourceManager.GetString("LabelTitleConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string LabelTitleContact {
            get {
                return ResourceManager.GetString("LabelTitleContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        internal static string LabelTitleDeal {
            get {
                return ResourceManager.GetString("LabelTitleDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity directory.
        /// </summary>
        internal static string LabelTitleDirectory {
            get {
                return ResourceManager.GetString("LabelTitleDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an address.
        /// </summary>
        internal static string LabelTitleEditAddress {
            get {
                return ResourceManager.GetString("LabelTitleEditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string LabelTitleEvent {
            get {
                return ResourceManager.GetString("LabelTitleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string LabelTitleForum {
            get {
                return ResourceManager.GetString("LabelTitleForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group messaging.
        /// </summary>
        internal static string LabelTitleGroupMessaging {
            get {
                return ResourceManager.GetString("LabelTitleGroupMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string LabelTitleMenu {
            get {
                return ResourceManager.GetString("LabelTitleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        internal static string LabelTitleMessaging {
            get {
                return ResourceManager.GetString("LabelTitleMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My neighbors.
        /// </summary>
        internal static string LabelTitleNeighbor {
            get {
                return ResourceManager.GetString("LabelTitleNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        internal static string LabelTitleOffer {
            get {
                return ResourceManager.GetString("LabelTitleOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit my profile.
        /// </summary>
        internal static string LabelTitleProfile {
            get {
                return ResourceManager.GetString("LabelTitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment rental.
        /// </summary>
        internal static string LabelTitleRental {
            get {
                return ResourceManager.GetString("LabelTitleRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange of services.
        /// </summary>
        internal static string LabelTitleServiceExchange {
            get {
                return ResourceManager.GetString("LabelTitleServiceExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string LabelTitleSetting {
            get {
                return ResourceManager.GetString("LabelTitleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solidarity Service.
        /// </summary>
        internal static string LabelTitleSolidarity {
            get {
                return ResourceManager.GetString("LabelTitleSolidarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls for solidarity.
        /// </summary>
        internal static string LabelTitleSolidarityCall {
            get {
                return ResourceManager.GetString("LabelTitleSolidarityCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solidarity offers.
        /// </summary>
        internal static string LabelTitleSolidarityOffer {
            get {
                return ResourceManager.GetString("LabelTitleSolidarityOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and pay.
        /// </summary>
        internal static string LabelValidationPay {
            get {
                return ResourceManager.GetString("LabelValidationPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        internal static string LabelZipcode {
            get {
                return ResourceManager.GetString("LabelZipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Española.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
